apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: myspringbootapp
spec:
  selector:
    app: myspringbootapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9099
    nodePort: 30036
